<?php

namespace App\Filament\Resources\Services\Pages;

use App\Filament\Resources\Services\ServiceResource;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateService extends CreateRecord
{
    protected static string $resource = ServiceResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('view', ['record' => $this->getRecord()]);
    }

    protected function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->success()
            ->title('Service créé avec succès')
            ->body('Le service a été créé et enregistré dans la base de données.');
    }

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()->label('Nouveau service')->icon('heroicon-o-plus'); // TODO: Change the autogenerated stub
    }

    protected function getCreateAnotherFormAction(): Action
    {
        return parent::getCreateAnotherFormAction()->label('Créer et ajouter un autre service'); // TODO: Change the autogenerated stub
    }
}
