# ==================================================
# GESTMAT V2 - AUTOMATED TESTS WORKFLOW
# ==================================================
# Runs on every pull request
# Copy to: .github/workflows/tests.yml
# ==================================================

name: Tests

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
  push:
    branches:
      - develop

env:
  PHP_VERSION: '8.4'
  NODE_VERSION: '20'

jobs:
  # ==================================================
  # Laravel Pint (Code Style)
  # ==================================================
  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Pint
        run: vendor/bin/pint --test

  # ==================================================
  # Pest Tests (Unit + Feature)
  # ==================================================
  pest:
    name: Pest Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: gestmatv2_test
          POSTGRES_USER: gestmat
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, pdo_pgsql, zip, gd, redis
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_DATABASE=gestmatv2_test" >> .env
          echo "DB_USERNAME=gestmat" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: php artisan test --parallel --coverage-clover coverage.xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml

  # ==================================================
  # Browser Tests (Pest v4)
  # ==================================================
  browser-tests:
    name: Browser Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: gestmatv2_test
          POSTGRES_USER: gestmat
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, pdo_pgsql, zip, gd, redis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction
          npm ci

      - name: Build assets
        run: npm run build

      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_DATABASE=gestmatv2_test" >> .env
          echo "DB_USERNAME=gestmat" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run browser tests
        run: php artisan test --filter=Browser

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: browser-test-screenshots
          path: tests/Browser/screenshots

  # ==================================================
  # Security Audit
  # ==================================================
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Security audit
        run: composer audit

      - name: Check for security issues
        run: |
          # Add additional security checks here
          # Example: using enlightn/security-checker
          # php artisan security:check
          echo "Security checks passed"
